[project]
name = "internet-archive"
version = "0.1.0"
description = "Archives a page of your choice to the Internet Archive"
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
